// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/services.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Topic struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Genre                string   `protobuf:"bytes,2,opt,name=Genre,proto3" json:"Genre,omitempty"`
	Hotness              int64    `protobuf:"varint,3,opt,name=Hotness,proto3" json:"Hotness,omitempty"`
	ID                   string   `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{0}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *Topic) GetHotness() int64 {
	if m != nil {
		return m.Hotness
	}
	return 0
}

func (m *Topic) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Person struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=Country,proto3" json:"Country,omitempty"`
	DOB                  int64    `protobuf:"varint,6,opt,name=DOB,proto3" json:"DOB,omitempty"`
	Age                  int64    `protobuf:"varint,7,opt,name=Age,proto3" json:"Age,omitempty"`
	TopicsIDs            []string `protobuf:"bytes,8,rep,name=TopicsIDs,proto3" json:"TopicsIDs,omitempty"`
	FriendsIDs           []string `protobuf:"bytes,9,rep,name=FriendsIDs,proto3" json:"FriendsIDs,omitempty"`
	ID                   string   `protobuf:"bytes,10,opt,name=ID,proto3" json:"ID,omitempty"`
	StoryIDs             []string `protobuf:"bytes,11,rep,name=StoryIDs,proto3" json:"StoryIDs,omitempty"`
	ReviewIDs            []string `protobuf:"bytes,12,rep,name=ReviewIDs,proto3" json:"ReviewIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Person) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Person) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Person) GetDOB() int64 {
	if m != nil {
		return m.DOB
	}
	return 0
}

func (m *Person) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetTopicsIDs() []string {
	if m != nil {
		return m.TopicsIDs
	}
	return nil
}

func (m *Person) GetFriendsIDs() []string {
	if m != nil {
		return m.FriendsIDs
	}
	return nil
}

func (m *Person) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Person) GetStoryIDs() []string {
	if m != nil {
		return m.StoryIDs
	}
	return nil
}

func (m *Person) GetReviewIDs() []string {
	if m != nil {
		return m.ReviewIDs
	}
	return nil
}

type Story struct {
	ID                   string   `protobuf:"bytes,8,opt,name=ID,proto3" json:"ID,omitempty"`
	Heading              string   `protobuf:"bytes,1,opt,name=Heading,proto3" json:"Heading,omitempty"`
	Story                []byte   `protobuf:"bytes,2,opt,name=Story,proto3" json:"Story,omitempty"`
	AuthorID             string   `protobuf:"bytes,5,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	AddTime              int64    `protobuf:"varint,6,opt,name=AddTime,proto3" json:"AddTime,omitempty"`
	EditTimes            []int64  `protobuf:"varint,7,rep,packed,name=EditTimes,proto3" json:"EditTimes,omitempty"`
	Genres               []string `protobuf:"bytes,3,rep,name=Genres,proto3" json:"Genres,omitempty"`
	MediaPaths           []string `protobuf:"bytes,4,rep,name=MediaPaths,proto3" json:"MediaPaths,omitempty"`
	TaggedPeopleIDs      []string `protobuf:"bytes,12,rep,name=TaggedPeopleIDs,proto3" json:"TaggedPeopleIDs,omitempty"`
	TopicsIDs            []string `protobuf:"bytes,9,rep,name=TopicsIDs,proto3" json:"TopicsIDs,omitempty"`
	Views                int64    `protobuf:"varint,10,opt,name=Views,proto3" json:"Views,omitempty"`
	ReviewIDs            []string `protobuf:"bytes,11,rep,name=ReviewIDs,proto3" json:"ReviewIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Story) Reset()         { *m = Story{} }
func (m *Story) String() string { return proto.CompactTextString(m) }
func (*Story) ProtoMessage()    {}
func (*Story) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{2}
}

func (m *Story) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Story.Unmarshal(m, b)
}
func (m *Story) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Story.Marshal(b, m, deterministic)
}
func (m *Story) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Story.Merge(m, src)
}
func (m *Story) XXX_Size() int {
	return xxx_messageInfo_Story.Size(m)
}
func (m *Story) XXX_DiscardUnknown() {
	xxx_messageInfo_Story.DiscardUnknown(m)
}

var xxx_messageInfo_Story proto.InternalMessageInfo

func (m *Story) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Story) GetHeading() string {
	if m != nil {
		return m.Heading
	}
	return ""
}

func (m *Story) GetStory() []byte {
	if m != nil {
		return m.Story
	}
	return nil
}

func (m *Story) GetAuthorID() string {
	if m != nil {
		return m.AuthorID
	}
	return ""
}

func (m *Story) GetAddTime() int64 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *Story) GetEditTimes() []int64 {
	if m != nil {
		return m.EditTimes
	}
	return nil
}

func (m *Story) GetGenres() []string {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *Story) GetMediaPaths() []string {
	if m != nil {
		return m.MediaPaths
	}
	return nil
}

func (m *Story) GetTaggedPeopleIDs() []string {
	if m != nil {
		return m.TaggedPeopleIDs
	}
	return nil
}

func (m *Story) GetTopicsIDs() []string {
	if m != nil {
		return m.TopicsIDs
	}
	return nil
}

func (m *Story) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *Story) GetReviewIDs() []string {
	if m != nil {
		return m.ReviewIDs
	}
	return nil
}

type Review struct {
	Heading              string   `protobuf:"bytes,1,opt,name=Heading,proto3" json:"Heading,omitempty"`
	ReviewerID           string   `protobuf:"bytes,2,opt,name=ReviewerID,proto3" json:"ReviewerID,omitempty"`
	AddTime              int64    `protobuf:"varint,3,opt,name=AddTime,proto3" json:"AddTime,omitempty"`
	Stars                int64    `protobuf:"varint,4,opt,name=Stars,proto3" json:"Stars,omitempty"`
	Review               []byte   `protobuf:"bytes,5,opt,name=Review,proto3" json:"Review,omitempty"`
	ID                   string   `protobuf:"bytes,6,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{3}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetHeading() string {
	if m != nil {
		return m.Heading
	}
	return ""
}

func (m *Review) GetReviewerID() string {
	if m != nil {
		return m.ReviewerID
	}
	return ""
}

func (m *Review) GetAddTime() int64 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *Review) GetStars() int64 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func (m *Review) GetReview() []byte {
	if m != nil {
		return m.Review
	}
	return nil
}

func (m *Review) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type AddStoryRequest struct {
	Story                *Story   `protobuf:"bytes,1,opt,name=Story,proto3" json:"Story,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddStoryRequest) Reset()         { *m = AddStoryRequest{} }
func (m *AddStoryRequest) String() string { return proto.CompactTextString(m) }
func (*AddStoryRequest) ProtoMessage()    {}
func (*AddStoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{4}
}

func (m *AddStoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStoryRequest.Unmarshal(m, b)
}
func (m *AddStoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStoryRequest.Marshal(b, m, deterministic)
}
func (m *AddStoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStoryRequest.Merge(m, src)
}
func (m *AddStoryRequest) XXX_Size() int {
	return xxx_messageInfo_AddStoryRequest.Size(m)
}
func (m *AddStoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddStoryRequest proto.InternalMessageInfo

func (m *AddStoryRequest) GetStory() *Story {
	if m != nil {
		return m.Story
	}
	return nil
}

type AddStoryResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddStoryResponse) Reset()         { *m = AddStoryResponse{} }
func (m *AddStoryResponse) String() string { return proto.CompactTextString(m) }
func (*AddStoryResponse) ProtoMessage()    {}
func (*AddStoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{5}
}

func (m *AddStoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddStoryResponse.Unmarshal(m, b)
}
func (m *AddStoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddStoryResponse.Marshal(b, m, deterministic)
}
func (m *AddStoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddStoryResponse.Merge(m, src)
}
func (m *AddStoryResponse) XXX_Size() int {
	return xxx_messageInfo_AddStoryResponse.Size(m)
}
func (m *AddStoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddStoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddStoryResponse proto.InternalMessageInfo

func (m *AddStoryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Topic)(nil), "services.Topic")
	proto.RegisterType((*Person)(nil), "services.Person")
	proto.RegisterType((*Story)(nil), "services.Story")
	proto.RegisterType((*Review)(nil), "services.Review")
	proto.RegisterType((*AddStoryRequest)(nil), "services.AddStoryRequest")
	proto.RegisterType((*AddStoryResponse)(nil), "services.AddStoryResponse")
}

func init() { proto.RegisterFile("services/services.proto", fileDescriptor_20616c573d3cd2a9) }

var fileDescriptor_20616c573d3cd2a9 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x8a, 0xdb, 0x30,
	0x10, 0x26, 0x71, 0xe2, 0x38, 0x93, 0xd0, 0x2c, 0x62, 0x69, 0xd5, 0x50, 0x96, 0x10, 0x28, 0xe4,
	0x50, 0xb6, 0xb0, 0xbd, 0xf4, 0xea, 0x6e, 0xba, 0x6d, 0xa0, 0x3f, 0x41, 0x09, 0xbd, 0xf4, 0xe4,
	0xc6, 0x43, 0x56, 0xd0, 0xb5, 0x52, 0x49, 0xd9, 0xc5, 0xaf, 0xd2, 0xc7, 0xe8, 0x8b, 0xf4, 0x95,
	0xca, 0x48, 0x96, 0x9d, 0x84, 0xb2, 0x37, 0x7d, 0xdf, 0x8c, 0x67, 0xbe, 0xf9, 0x46, 0x32, 0x3c,
	0x33, 0xa8, 0xef, 0xe5, 0x06, 0xcd, 0xeb, 0x70, 0xb8, 0xdc, 0x69, 0x65, 0x15, 0x4b, 0x02, 0x9e,
	0x7e, 0x87, 0xee, 0x5a, 0xed, 0xe4, 0x86, 0x31, 0xe8, 0x7c, 0xc9, 0xee, 0x90, 0xb7, 0x26, 0xad,
	0x59, 0x5f, 0xb8, 0x33, 0x3b, 0x87, 0xee, 0x07, 0x2c, 0x34, 0xf2, 0xb6, 0x23, 0x3d, 0x60, 0x1c,
	0x7a, 0x1f, 0x95, 0x2d, 0xd0, 0x18, 0x1e, 0x4d, 0x5a, 0xb3, 0x48, 0x04, 0xc8, 0x9e, 0x40, 0x7b,
	0x31, 0xe7, 0x1d, 0x97, 0xdc, 0x5e, 0xcc, 0xa7, 0x7f, 0xda, 0x10, 0x2f, 0x51, 0x1b, 0x55, 0xb0,
	0x17, 0xd0, 0xbf, 0x91, 0xda, 0xd8, 0x83, 0x1e, 0x0d, 0xc1, 0xc6, 0x90, 0x7c, 0xca, 0xaa, 0xa0,
	0xef, 0x55, 0x63, 0x12, 0x76, 0x2d, 0x6d, 0xe9, 0x7a, 0xf5, 0x85, 0x3b, 0x93, 0xb0, 0x95, 0xcd,
	0x2c, 0x56, 0xbd, 0x3c, 0x20, 0x61, 0xd7, 0x6a, 0x5f, 0x58, 0x5d, 0xf2, 0xae, 0xe3, 0x03, 0x64,
	0x67, 0x10, 0xcd, 0xbf, 0xbe, 0xe3, 0xb1, 0x93, 0x4b, 0x47, 0x62, 0xd2, 0x2d, 0xf2, 0x9e, 0x67,
	0xd2, 0x2d, 0x92, 0x42, 0xe7, 0x84, 0x59, 0xcc, 0x0d, 0x4f, 0x26, 0x11, 0x29, 0xac, 0x09, 0x76,
	0x01, 0x70, 0xa3, 0x25, 0x16, 0xb9, 0x0b, 0xf7, 0x5d, 0xf8, 0x80, 0xa9, 0x46, 0x87, 0x30, 0x3a,
	0x4d, 0xb4, 0xb2, 0x4a, 0x97, 0x94, 0x3d, 0x70, 0xd9, 0x35, 0xa6, 0x4e, 0x02, 0xef, 0x25, 0x3e,
	0x50, 0x70, 0xe8, 0x3b, 0xd5, 0xc4, 0xf4, 0x6f, 0x9b, 0x86, 0x53, 0xba, 0xac, 0x6a, 0x26, 0x75,
	0x4d, 0x32, 0x1e, 0xb3, 0x5c, 0x16, 0xdb, 0xca, 0xc1, 0x00, 0xbd, 0x1f, 0x4a, 0x97, 0xce, 0xbc,
	0xa1, 0xa8, 0xbe, 0x1f, 0x43, 0x92, 0xee, 0xed, 0xad, 0xd2, 0x8b, 0x79, 0x65, 0x48, 0x8d, 0xa9,
	0x56, 0x9a, 0xe7, 0x6b, 0x79, 0x87, 0x95, 0x2b, 0x01, 0x92, 0xba, 0xf7, 0xb9, 0xb4, 0x74, 0x36,
	0xbc, 0x37, 0x89, 0x66, 0x91, 0x68, 0x08, 0xf6, 0x14, 0x62, 0x77, 0x0b, 0x68, 0xf7, 0x24, 0xbc,
	0x42, 0xe4, 0xcf, 0x67, 0xcc, 0x65, 0xb6, 0xcc, 0xec, 0xad, 0xe1, 0x1d, 0xef, 0x4f, 0xc3, 0xb0,
	0x19, 0x8c, 0xd6, 0xd9, 0x76, 0x8b, 0xf9, 0x12, 0xd5, 0xee, 0x27, 0x36, 0x93, 0x9f, 0xd2, 0xc7,
	0x7b, 0xe8, 0x9f, 0xee, 0xe1, 0x1c, 0xba, 0xdf, 0x24, 0x3e, 0x18, 0x67, 0x75, 0x24, 0x3c, 0x38,
	0x76, 0x74, 0x70, 0xea, 0xe8, 0xef, 0x16, 0xc4, 0x1e, 0x3d, 0x62, 0xe1, 0x05, 0x80, 0xcf, 0x41,
	0xb2, 0xcb, 0x5f, 0xc2, 0x03, 0xe6, 0xd0, 0xb0, 0xe8, 0xd8, 0x30, 0x7f, 0x19, 0xb5, 0x71, 0x97,
	0x31, 0x12, 0x1e, 0x90, 0x51, 0xfe, 0x6b, 0x67, 0xfd, 0x50, 0x04, 0x05, 0x7e, 0xa9, 0x71, 0xfd,
	0x46, 0xde, 0xc2, 0x28, 0xcd, 0x73, 0xb7, 0x30, 0x81, 0xbf, 0xf6, 0x68, 0x2c, 0x7b, 0x19, 0xb6,
	0x49, 0x12, 0x07, 0x57, 0xa3, 0xcb, 0xfa, 0xf5, 0xfa, 0x34, 0x1f, 0x9d, 0xbe, 0x82, 0xb3, 0xe6,
	0x4b, 0xb3, 0x53, 0x85, 0x71, 0x4f, 0x60, 0xb5, 0xdf, 0x6c, 0xe8, 0x6d, 0xd2, 0xc7, 0x89, 0x08,
	0xf0, 0x6a, 0x0d, 0x23, 0x4a, 0x45, 0x34, 0xab, 0xaa, 0x1a, 0x4b, 0x21, 0x09, 0x05, 0xd8, 0xf3,
	0xa6, 0xc9, 0x89, 0x9c, 0xf1, 0xf8, 0x7f, 0x21, 0xdf, 0xef, 0x47, 0xec, 0xfe, 0x27, 0x6f, 0xfe,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x44, 0x5f, 0x78, 0x45, 0x6a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreesServicesClient is the client API for StoreesServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreesServicesClient interface {
	AddStory(ctx context.Context, in *AddStoryRequest, opts ...grpc.CallOption) (*AddStoryResponse, error)
}

type storeesServicesClient struct {
	cc *grpc.ClientConn
}

func NewStoreesServicesClient(cc *grpc.ClientConn) StoreesServicesClient {
	return &storeesServicesClient{cc}
}

func (c *storeesServicesClient) AddStory(ctx context.Context, in *AddStoryRequest, opts ...grpc.CallOption) (*AddStoryResponse, error) {
	out := new(AddStoryResponse)
	err := c.cc.Invoke(ctx, "/services.StoreesServices/AddStory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreesServicesServer is the server API for StoreesServices service.
type StoreesServicesServer interface {
	AddStory(context.Context, *AddStoryRequest) (*AddStoryResponse, error)
}

// UnimplementedStoreesServicesServer can be embedded to have forward compatible implementations.
type UnimplementedStoreesServicesServer struct {
}

func (*UnimplementedStoreesServicesServer) AddStory(ctx context.Context, req *AddStoryRequest) (*AddStoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStory not implemented")
}

func RegisterStoreesServicesServer(s *grpc.Server, srv StoreesServicesServer) {
	s.RegisterService(&_StoreesServices_serviceDesc, srv)
}

func _StoreesServices_AddStory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreesServicesServer).AddStory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.StoreesServices/AddStory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreesServicesServer).AddStory(ctx, req.(*AddStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreesServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.StoreesServices",
	HandlerType: (*StoreesServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddStory",
			Handler:    _StoreesServices_AddStory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/services.proto",
}
