// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/services.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Topic struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Genre                string   `protobuf:"bytes,2,opt,name=Genre,proto3" json:"Genre,omitempty"`
	Hotness              int64    `protobuf:"varint,3,opt,name=Hotness,proto3" json:"Hotness,omitempty"`
	ID                   string   `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{0}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *Topic) GetHotness() int64 {
	if m != nil {
		return m.Hotness
	}
	return 0
}

func (m *Topic) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Person struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=Country,proto3" json:"Country,omitempty"`
	DOB                  int64    `protobuf:"varint,6,opt,name=DOB,proto3" json:"DOB,omitempty"`
	Age                  int64    `protobuf:"varint,7,opt,name=Age,proto3" json:"Age,omitempty"`
	TopicsIDs            []string `protobuf:"bytes,8,rep,name=TopicsIDs,proto3" json:"TopicsIDs,omitempty"`
	FriendsIDs           []string `protobuf:"bytes,9,rep,name=FriendsIDs,proto3" json:"FriendsIDs,omitempty"`
	ID                   string   `protobuf:"bytes,10,opt,name=ID,proto3" json:"ID,omitempty"`
	StoryIDs             []string `protobuf:"bytes,11,rep,name=StoryIDs,proto3" json:"StoryIDs,omitempty"`
	ReviewIDs            []string `protobuf:"bytes,12,rep,name=ReviewIDs,proto3" json:"ReviewIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Person) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Person) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Person) GetDOB() int64 {
	if m != nil {
		return m.DOB
	}
	return 0
}

func (m *Person) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetTopicsIDs() []string {
	if m != nil {
		return m.TopicsIDs
	}
	return nil
}

func (m *Person) GetFriendsIDs() []string {
	if m != nil {
		return m.FriendsIDs
	}
	return nil
}

func (m *Person) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Person) GetStoryIDs() []string {
	if m != nil {
		return m.StoryIDs
	}
	return nil
}

func (m *Person) GetReviewIDs() []string {
	if m != nil {
		return m.ReviewIDs
	}
	return nil
}

type Story struct {
	ID                   string   `protobuf:"bytes,8,opt,name=ID,proto3" json:"ID,omitempty"`
	Heading              string   `protobuf:"bytes,1,opt,name=Heading,proto3" json:"Heading,omitempty"`
	Story                []byte   `protobuf:"bytes,2,opt,name=Story,proto3" json:"Story,omitempty"`
	AuthorID             string   `protobuf:"bytes,5,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	AddTime              int64    `protobuf:"varint,6,opt,name=AddTime,proto3" json:"AddTime,omitempty"`
	EditTimes            []int64  `protobuf:"varint,7,rep,packed,name=EditTimes,proto3" json:"EditTimes,omitempty"`
	Genres               []string `protobuf:"bytes,3,rep,name=Genres,proto3" json:"Genres,omitempty"`
	MediaPaths           []string `protobuf:"bytes,4,rep,name=MediaPaths,proto3" json:"MediaPaths,omitempty"`
	TaggedPeopleIDs      []string `protobuf:"bytes,12,rep,name=TaggedPeopleIDs,proto3" json:"TaggedPeopleIDs,omitempty"`
	TopicsIDs            []string `protobuf:"bytes,9,rep,name=TopicsIDs,proto3" json:"TopicsIDs,omitempty"`
	Views                int64    `protobuf:"varint,10,opt,name=Views,proto3" json:"Views,omitempty"`
	ReviewIDs            []string `protobuf:"bytes,11,rep,name=ReviewIDs,proto3" json:"ReviewIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Story) Reset()         { *m = Story{} }
func (m *Story) String() string { return proto.CompactTextString(m) }
func (*Story) ProtoMessage()    {}
func (*Story) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{2}
}

func (m *Story) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Story.Unmarshal(m, b)
}
func (m *Story) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Story.Marshal(b, m, deterministic)
}
func (m *Story) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Story.Merge(m, src)
}
func (m *Story) XXX_Size() int {
	return xxx_messageInfo_Story.Size(m)
}
func (m *Story) XXX_DiscardUnknown() {
	xxx_messageInfo_Story.DiscardUnknown(m)
}

var xxx_messageInfo_Story proto.InternalMessageInfo

func (m *Story) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Story) GetHeading() string {
	if m != nil {
		return m.Heading
	}
	return ""
}

func (m *Story) GetStory() []byte {
	if m != nil {
		return m.Story
	}
	return nil
}

func (m *Story) GetAuthorID() string {
	if m != nil {
		return m.AuthorID
	}
	return ""
}

func (m *Story) GetAddTime() int64 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *Story) GetEditTimes() []int64 {
	if m != nil {
		return m.EditTimes
	}
	return nil
}

func (m *Story) GetGenres() []string {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *Story) GetMediaPaths() []string {
	if m != nil {
		return m.MediaPaths
	}
	return nil
}

func (m *Story) GetTaggedPeopleIDs() []string {
	if m != nil {
		return m.TaggedPeopleIDs
	}
	return nil
}

func (m *Story) GetTopicsIDs() []string {
	if m != nil {
		return m.TopicsIDs
	}
	return nil
}

func (m *Story) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *Story) GetReviewIDs() []string {
	if m != nil {
		return m.ReviewIDs
	}
	return nil
}

type Review struct {
	Heading              string   `protobuf:"bytes,1,opt,name=Heading,proto3" json:"Heading,omitempty"`
	ReviewerID           string   `protobuf:"bytes,2,opt,name=ReviewerID,proto3" json:"ReviewerID,omitempty"`
	AddTime              int64    `protobuf:"varint,3,opt,name=AddTime,proto3" json:"AddTime,omitempty"`
	Stars                int64    `protobuf:"varint,4,opt,name=Stars,proto3" json:"Stars,omitempty"`
	Review               []byte   `protobuf:"bytes,5,opt,name=Review,proto3" json:"Review,omitempty"`
	ID                   string   `protobuf:"bytes,6,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_20616c573d3cd2a9, []int{3}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetHeading() string {
	if m != nil {
		return m.Heading
	}
	return ""
}

func (m *Review) GetReviewerID() string {
	if m != nil {
		return m.ReviewerID
	}
	return ""
}

func (m *Review) GetAddTime() int64 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *Review) GetStars() int64 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func (m *Review) GetReview() []byte {
	if m != nil {
		return m.Review
	}
	return nil
}

func (m *Review) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*Topic)(nil), "services.Topic")
	proto.RegisterType((*Person)(nil), "services.Person")
	proto.RegisterType((*Story)(nil), "services.Story")
	proto.RegisterType((*Review)(nil), "services.Review")
}

func init() { proto.RegisterFile("services/services.proto", fileDescriptor_20616c573d3cd2a9) }

var fileDescriptor_20616c573d3cd2a9 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4b, 0x6e, 0xdb, 0x30,
	0x10, 0x86, 0x61, 0xd1, 0x96, 0xa5, 0x89, 0xd1, 0x16, 0x44, 0xd0, 0x12, 0x41, 0x11, 0x18, 0x5e,
	0x79, 0xd5, 0x2e, 0x7a, 0x02, 0x37, 0x6a, 0x5a, 0x03, 0x7d, 0x18, 0x8c, 0xd1, 0x4d, 0x57, 0x6a,
	0x34, 0x50, 0x08, 0x34, 0xa2, 0x41, 0x32, 0x09, 0x74, 0x95, 0x1e, 0xa3, 0x17, 0xe9, 0x95, 0x8a,
	0xe1, 0x43, 0x7e, 0x2c, 0xba, 0xe3, 0xff, 0x93, 0xe2, 0xfc, 0xf3, 0x0d, 0x05, 0xaf, 0x2c, 0x9a,
	0x47, 0x75, 0x8b, 0xf6, 0x6d, 0x5a, 0xbc, 0xd9, 0x19, 0xed, 0x34, 0x2f, 0x92, 0x5e, 0xfc, 0x80,
	0xc9, 0x56, 0xef, 0xd4, 0x2d, 0xe7, 0x30, 0xfe, 0x5a, 0xdf, 0xa3, 0x18, 0xcd, 0x47, 0xcb, 0x52,
	0xfa, 0x35, 0x3f, 0x87, 0xc9, 0x47, 0xec, 0x0c, 0x8a, 0xcc, 0x9b, 0x41, 0x70, 0x01, 0xd3, 0x4f,
	0xda, 0x75, 0x68, 0xad, 0x60, 0xf3, 0xd1, 0x92, 0xc9, 0x24, 0xf9, 0x33, 0xc8, 0xd6, 0x95, 0x18,
	0xfb, 0xc3, 0xd9, 0xba, 0x5a, 0xfc, 0xc9, 0x20, 0xdf, 0xa0, 0xb1, 0xba, 0xe3, 0xaf, 0xa1, 0xbc,
	0x56, 0xc6, 0xba, 0x83, 0x1a, 0x7b, 0x83, 0x5f, 0x40, 0xf1, 0xb9, 0x8e, 0x9b, 0xa1, 0xd6, 0xa0,
	0x29, 0xd8, 0x95, 0x72, 0xbd, 0xaf, 0x55, 0x4a, 0xbf, 0xa6, 0x60, 0x37, 0xae, 0x76, 0x18, 0x6b,
	0x05, 0x41, 0xc1, 0xae, 0xf4, 0x43, 0xe7, 0x4c, 0x2f, 0x26, 0xde, 0x4f, 0x92, 0xbf, 0x00, 0x56,
	0x7d, 0x7b, 0x2f, 0x72, 0x1f, 0x97, 0x96, 0xe4, 0xac, 0x5a, 0x14, 0xd3, 0xe0, 0xac, 0x5a, 0xa4,
	0x84, 0x9e, 0x84, 0x5d, 0x57, 0x56, 0x14, 0x73, 0x46, 0x09, 0x07, 0x83, 0x5f, 0x02, 0x5c, 0x1b,
	0x85, 0x5d, 0xe3, 0xb7, 0x4b, 0xbf, 0x7d, 0xe0, 0xc4, 0xd6, 0x21, 0xb5, 0x4e, 0x1d, 0xdd, 0x38,
	0x6d, 0x7a, 0x3a, 0x7d, 0xe6, 0x4f, 0x0f, 0x9a, 0x2a, 0x49, 0x7c, 0x54, 0xf8, 0x44, 0x9b, 0xb3,
	0x50, 0x69, 0x30, 0x16, 0x7f, 0x33, 0x6a, 0x4e, 0x9b, 0x3e, 0xde, 0x59, 0x0c, 0x77, 0x12, 0x78,
	0xac, 0x1b, 0xd5, 0xb5, 0x91, 0x60, 0x92, 0x81, 0x87, 0x36, 0xbd, 0x87, 0x37, 0x93, 0xf1, 0xfb,
	0x0b, 0x28, 0x56, 0x0f, 0xee, 0x4e, 0x9b, 0x75, 0x15, 0x81, 0x0c, 0x9a, 0xee, 0x5a, 0x35, 0xcd,
	0x56, 0xdd, 0x63, 0xa4, 0x92, 0x24, 0xa5, 0xfb, 0xd0, 0x28, 0x47, 0x6b, 0x2b, 0xa6, 0x73, 0xb6,
	0x64, 0x72, 0x6f, 0xf0, 0x97, 0x90, 0xfb, 0x57, 0x40, 0xb3, 0xa7, 0xe0, 0x51, 0x11, 0x9f, 0x2f,
	0xd8, 0xa8, 0x7a, 0x53, 0xbb, 0x3b, 0x2b, 0xc6, 0x81, 0xcf, 0xde, 0xe1, 0x4b, 0x78, 0xbe, 0xad,
	0xdb, 0x16, 0x9b, 0x0d, 0xea, 0xdd, 0x2f, 0xdc, 0x77, 0x7e, 0x6a, 0x1f, 0xcf, 0xa1, 0x3c, 0x9d,
	0xc3, 0x39, 0x4c, 0xbe, 0x2b, 0x7c, 0xb2, 0x1e, 0x35, 0x93, 0x41, 0x1c, 0x13, 0x3d, 0x3b, 0x25,
	0xfa, 0x7b, 0x04, 0x79, 0x50, 0xff, 0x41, 0x78, 0x09, 0x10, 0xce, 0x20, 0xe1, 0x0a, 0x8f, 0xf0,
	0xc0, 0x39, 0x04, 0xc6, 0x8e, 0x81, 0x85, 0xc7, 0x68, 0xac, 0x7f, 0x8c, 0x4c, 0x06, 0x41, 0xa0,
	0xc2, 0xd7, 0x1e, 0xfd, 0x4c, 0xa6, 0x04, 0x61, 0xa8, 0x79, 0x1a, 0xea, 0xcf, 0xdc, 0xff, 0x91,
	0xef, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xd2, 0x16, 0xee, 0xac, 0x03, 0x00, 0x00,
}
